### ISSUE TITLE
request missing critical parameter `?d=`

### ISSUE THREAD

**Issue by TITC** [Layout-Parser/annotation-service#3]
1. [error position
](https://github.com/Layout-Parser/annotation-service/blob/50dbde27bb916b51ec1cd40bbe72fc9397042b15/modeling/tools/model.py#L34)
2. error info
```shell
172.18.0.2 - - [09/Jan/2022 12:40:25] "POST /predict HTTP/1.1" 500 -
172.18.0.2 - - [09/Jan/2022 12:41:59] "GET /health HTTP/1.1" 200 -
172.18.0.2 - - [09/Jan/2022 12:42:02] "POST /setup HTTP/1.1" 200 -
****************************************************************************************************
tasks [{'id': 3, 'data': {'image': 'http://localhost:8080/data/upload/60bde0802278ca3bf0fe4bec3eaf8bac-1100000206088611_9.jpg'}, 'predictions': []}]
****************************************************************************************************
**************************************************
url http://localhost:8080/data/upload/60bde0802278ca3bf0fe4bec3eaf8bac-1100000206088611_9.jpg
**************************************************
[2022-01-09 12:42:04,068] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/label_studio/ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(
  File "/usr/local/lib/python3.8/dist-packages/label_studio/ml/model.py", line 264, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/annotation_service_modeling/modeling_backend/model.py", line 102, in predict
    images = [load_image_from_url(url) for url in image_urls]
  File "/annotation_service_modeling/modeling_backend/model.py", line 102, in <listcomp>
    images = [load_image_from_url(url) for url in image_urls]
  File "/annotation_service_modeling/modeling_backend/model.py", line 36, in load_image_from_url
    filename, dir_path = url.split('/data/')[1].split('?d=')
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by lolipopshock** [comment]
I'm so sorry I just saw your issue.. Perhaps this is caused by a different label-studio version?
